### ISSUE TITLE
Bug Report: -m option seg faults with values over 2000-ish

### ISSUE THREAD

**Issue by galiagante** [Dasio/pcfg-manager#1]
Built with go version go1.11.2 linux/amd64

Attempts to assign the '-m' values in excess of approx 2000, I see a failure (below). Partial generation of results does occur, however. Use in combination with other options does not appear to alter this failure.

    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x52b5b6]

    goroutine 1 [running]:
    github.com/dasio/pcfg-manager/manager.(*GuessGeneration).Init(0xc0001f1a40, 0xc0000111d0, 0x0)
        /home/galiagante/projects/wordlists/password_research/pcfg-manager/manager/guess.go:126 +0xc6
    github.com/dasio/pcfg-manager/manager.NewGuessGeneration(0xc0000ac1e0, 0xc0000111d0, 0x23)
        /home/galiagante/projects/wordlists/password_research/pcfg-manager/manager/guess.go:117 +0x64
    github.com/dasio/pcfg-manager/manager.(*Pcfg).ListTerminals(0xc00000e5d8, 0xc0000111d0, 0x0, 0x0, 0x5, 0x0, 0x0)
        /home/galiagante/projects/wordlists/password_research/pcfg-manager/manager/pcfg.go:36 +0x50
    github.com/dasio/pcfg-manager/manager.(*Generator).Run(0xc000011080, 0x79b1a0, 0x2, 0xc000155848)
        /home/galiagante/projects/wordlists/password_research/pcfg-manager/manager/generator.go:72 +0x5e
    github.com/dasio/pcfg-manager/manager.(*Manager).Start(0xc0000bdcc8, 0x79b1a0, 0x0, 0xc0000bdcc8)
        /home/galiagante/projects/wordlists/password_research/pcfg-manager/manager/manager.go:32 +0x239
    github.com/dasio/pcfg-manager/cmd.glob..func1(0x77b9a0, 0xc00000c260, 0x0, 0x2, 0x0, 0x0)
        /home/galiagante/projects/wordlists/password_research/pcfg-manager/cmd/root.go:22 +0x93
    github.com/spf13/cobra.(*Command).execute(0x77b9a0, 0xc000010190, 0x2, 0x2, 0x77b9a0, 0xc000010190)
        /home/galiagante/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:762 +0x473
    github.com/spf13/cobra.(*Command).ExecuteC(0x77b9a0, 0xc0000bdf40, 0xc0000bdf58, 0xc0000bdf88)
        /home/galiagante/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2fd
    github.com/spf13/cobra.(*Command).Execute(0x77b9a0, 0xc0000bdf78, 0x58e1c9)
        /home/galiagante/go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800 +0x2b
    github.com/dasio/pcfg-manager/cmd.Execute(0xc0000bdf88, 0xc00001a118)
        /home/galiagante/projects/wordlists/password_research/pcfg-manager/cmd/root.go:30 +0x2d
    main.main()
        /home/galiagante/projects/wordlists/password_research/pcfg-manager/main.go:19 +0x22

**Comment by Dasio** [comment]
If it would be possible to send me grammar at least in PM it would be great. What means "2000-ish"? Does it seg fault without -m?
Does it segfault using https://github.com/lakiw/pcfg_cracker/tree/master/python_pcfg_cracker?

**Comment by galiagante** [comment]
Apologies for the delay in responding.

There may be other issues at play here? After a fresh 'git pull" I seem to be unable to build this application:

    $ go build
    # bytes
    /usr/local/go/src/bytes/bytes_decl.go:10:6: IndexByte redeclared in this block
	previous declaration at /usr/local/go/src/bytes/bytes.go:101:34
    /usr/local/go/src/bytes/bytes_decl.go:17:6: Equal redeclared in this block
	previous declaration at /usr/local/go/src/bytes/bytes.go:18:25
    /usr/local/go/src/bytes/bytes_decl.go:24:6: Compare redeclared in this block
	previous declaration at /usr/local/go/src/bytes/bytes.go:37:27
    # strings
    /usr/local/go/src/strings/strings_decl.go:8:6: IndexByte redeclared in this block
	previous declaration at /usr/local/go/src/strings/strings.go:150:34

I will go back through my notes and verify the commands I was using when I ran into the error originally mentioned in the Issue.

**Comment by galiagante** [comment]
Some more details:
- I was using a basic "1000 Worst Passwords" list as a training set.
- I appear to be getting segfaults both with and without specifying '-m' as an option, afer displaying roughly 2050 passwords.

The error message reads:
    panic: runtime error: invalid memory address or nil pointer dereference
    [signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x52b5b6]

Some additional debugging information was located:
    INFO[0000] Config file loaded
    INFO[0000] Rule:  Default
    INFO[0000] GoRoutines:  1
    INFO[0000] MaxGuesses:  0
    INFO[0000] Debug:  false

**Comment by Dasio** [comment]
It's probably because of my generator is not supporting markov generator.
Try run trainer with `--coverage 1`
